on:
  workflow_dispatch:
  push:
  
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          image: ubuntu:20.04
          deps: |
            # Update packages
            apt update 
            # Install ubuntu dependencies
            DEBIAN_FRONTEND=noninteractive apt install -y git libc-dev libxi-dev libx11-dev libxcursor-dev cmake clang libssl-dev libpulse-dev libxrandr-dev libxinerama-dev libcurl4-openssl-dev
            # Install fake x11 server for tests
            DEBIAN_FRONTEND=noninteractive apt install -y xserver-xorg-video-dummy libgl1-mesa-dri
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.image || '' }}
    name: ${{ matrix.image || matrix.os }}
    steps:
    - name: Install Dependencies
      run: ${{ matrix.deps }}
      if: ${{ matrix.deps }}
    - name: Get Sources
      run: |
        git clone https://github.com/minecraft-linux/mcpelauncher-archive mcpelauncher
        git -C mcpelauncher checkout "$GITHUB_SHA"
    - name: CMake Configure
      run: |
        cmake -S mcpelauncher -B build -DBUILD_WEBVIEW=OFF -DENABLE_QT_ERROR_UI=OFF -DGAMEWINDOW_SYSTEM=GLFW -DJNI_USE_JNIVM=ON
      env:
        CC: clang
        CXX: clang++
    - name: CMake Build
      run: |
        cmake --build build --parallel
    - name: Pack
      run: |
        tar -cf ./release.tar build/
    - uses: actions/upload-artifact@v3
      with:
        name: build-${{ strategy.job-index }}
        path: release.tar
